Add Coinomi 3rd party wallet
PIVX-Project/PIVX-Doc-Website-Content pull request #13
Opened 2024-07-14 16:22 UTC by PalmTreeVI

Add Coinomi wallet to 3rd party wallets and added missing link for CoinSpot.

2024-07-14 17:39 UTC, Liquid369 submitted a review, later dismissed
ACK 72a5b1472f3caf03231b5fa39fe447c043f4afc8

2024-07-22 14:54 UTC, JSKitty requested changes

2024-07-22 14:54 UTC, JSKitty commented on 02.wallets/article.md
> +The [Coinomi](https://www.coinomi.com/) is a multi asset wallet that works on desktop or mobile hardware.
It currently reads "The Coinomi is a multi asset wallet [...]", perhaps it should be:
```suggestion
The [Coinomi](https://www.coinomi.com/) wallet is a multi asset wallet that works on desktop or mobile hardware.  
```

---

**Additionally... in my opinion:** due to quite a lot of shady history and **[extremely bad security practices](https://www.avoid-coinomi.com/)**, there should perhaps be a warning about Coinomi regarding safety and security.

2024-07-22 15:22 UTC, JSKitty approved these changes
ACK

2025-01-12 22:58 UTC, Liquid369 approved these changes
ACK 8e0252601236961b53abbc3b350fc1fec0d9bb96

2025-01-12 23:01 UTC, merged