add Mastodon and Rumble
PIVX-Project/PIVX-Doc-Website-Content pull request #15
Opened 2024-07-14 17:56 UTC by PalmTreeVI

2024-07-19 21:18 UTC, Liquid369 approved these changes, later dismissed
ACK 90e5ba47839e0bbb0a020179bcd10187ca02b0ca

2024-07-22 14:40 UTC, JSKitty requested changes

2024-07-22 14:40 UTC, JSKitty commented on 06.community/article.md
> +* Mastadon: https://mastodon.social/@pivxcrypto/
Typo
```suggestion
* Mastodon: https://mastodon.social/@pivxcrypto/
```

2024-07-22 14:52 UTC, Liquid369 approved these changes
ACK 30900fabe8fb972ebd62e906ec2aba006130627d

2024-07-22 14:55 UTC, JSKitty approved these changes
ACK

2024-07-22 14:57 UTC, merged